### ISSUE TITLE
Can MONeT use for Transformer model?

### ISSUE THREAD

**Issue by ghosthamlet** [utsaslab/MONeT#2]
The usage in README is all about CNN models, can it run with Transformer models?
And why create a solution have to Obtain the Gurobi academic license?

**Comment by aashaka** [comment]
We are working on making MONeT work for Transformers. We need to add a few operation implementations like GeLU and Embeddings for that.

We solve a binary programming problem for obtaining a checkpointing schedule with minimal compute overhead. Since we use a Gurobi solver to solve the problem, a license is required. You can use an open-source solver like cbc (cvxpy_solver.py takes in solver type as an argument), but Gurobi solves the schedules way faster.

**Comment by ghosthamlet** [comment]
Thanks, i got it, can't wait to see the Transformers support.
