### ISSUE TITLE
How to use MONet for training with larger batch sizes?

### ISSUE THREAD

**Issue by merrymercy** [utsaslab/MONeT#3]
Hi, thanks for the awesome library.

One of the biggest purposes of saving memory is to enable traninig with larger batch sizes.
How to use MONet to do this? Specifically, 

1. Do I need to change objective functions and constraints? Checkmate discussed this in the section 6.4 of its paper. How can we do this in MONet?
2. If I do not want to run the solver for every new batch size, can I reuse computed schedule solutions for different and larger batch sizes? How will it affect the memory saving and overhead?
3. If I want to test the maximum batch size I can achieve with MONet, how can I do this?

**Comment by aashaka** [comment]
Hi, thanks for trying it out.

1. MONeT's optimization problem aims to minimize the compute cost for a given batch size and memory budget. As mentioned in section 6.4 of Checkmate, building an optimization problem to maximize the batch size will lead to quadratic constraints, making the problem more difficult to solve. Instead, I would suggest a different (untested as of now) modification to MONeT's formulation in order to programmatically get maximum batch size - fix a batch size (ideally the batch size which just fits the GPU) and minimize the memory budget while fixing the compute overhead. Use the obtained MONeT schedule with the maximum batch size obtained by scaling the original batch size with a scale factor of `machine_memory/minimum_memory_budget`.

2. Yes. You need not recompute the schedules for each batch size. The schedules can be used for other batch sizes and will use memory proportional to the batch size increase while keeping the same compute overhead. This is another way you can obtain a schedule for training with the maximum batch size. We have provided a schedule zoo for this exact reason. 
For example, we can train Resnet-50 using a batch size of 416 on a P100 GPU using a schedule obtained for batch size 184 and memory budget 6GB. The memory used increases by 2.22x and computation time by 2.23x, which is nearly the same as the batch size increase of 2.27x.

3. I hope the above answers and the answer to issue 4 will help you get started with it.

**Comment by merrymercy** [comment]
Thanks for the excellent answer!
